export default {
  global: {
    RESET_STATE: 'GLOBAL_RESET_STATE',
    LOADING: 'LOADING',
    CONNEXION_BY_FORM: 'CONNEXION_BY_FORM',
    DATA_INITIALIZED: 'DATA_INITIALIZED'
  },
  auth: {
    REQUEST: 'AUTH_REQUEST',
    REDIRECT: 'AUTH_REDIRECT',
    SUCCESS: 'AUTH_SUCCESS',
    ERROR: 'AUTH_ERROR',
    LOGOUT: 'AUTH_LOGOUT',
    REFRESH: 'AUTH_REFRESH',
    REFRESH_SUCCESS: 'AUTH_REFRESH_SUCCESS',
    REDIRECT_CONNEXION: 'AUTH_REDIRECT_CONNEXION'
  },
  account: {
    REGISTER: 'REGISTER',
    REGISTER_SUCCESS: 'REGISTER_SUCCESS',
    REGISTER_ERROR: 'REGISTER_ERROR',
    FORGOT_PASSWORD: 'FORGOT_PASSWORD',
    RESET_PASSWORD: 'RESET_PASSWORD'
  },
  cropper: {
    RESET_ALL: 'CROPPER_RESET',
    SET_IMGSRC: 'CROPPER_SET_IMGSRC',
    SET_IMGCROP: 'CROPPER_SET_IMGCROP',
    IMG_HEIGHT: 'CROPPER_IMG_HEIGHT',
    IMG_WIDTH: 'CROPPER_IMG_WIDTH'
  },
  profile: {
    REQUEST: 'PROFILE_REQUEST'
  },
  user: {
    REQUEST: 'USER_REQUEST',
    SUCCESS: 'USER_SUCCESS',
    ERROR: 'USER_ERROR',
    LOGOUT: 'USER_LOGOUT'
  },
  selected: {
    RESET_STATE: 'SELECTED_RESET_STATE',
    CHANGE_LANGUAGE: 'CHANGE_LANGUAGE'
  }
}
